//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrozenCode.Community.Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public short Id { get; set; }
        public string FullName { get; set; }
        public string FatherName { get; set; }
        public string GrandFatherName { get; set; }
        public string Address { get; set; }
        public string Mobile { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.DateTime> MarriageDate { get; set; }
        public string EducationQualification { get; set; }
        public string MemberID { get; set; }
        public string ImageLocation { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdaatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
